/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package connecthub;

import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.security.NoSuchAlgorithmException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author mohamed
 */
public class SignUpGUI extends javax.swing.JFrame {
    private UserAccountManagement userAccountManagement;
    private UserAccountManagmentGUI loginFrame;
    private ConnectHubEngine cEngine;


    
    public SignUpGUI(UserAccountManagement userAccountManagement, UserAccountManagmentGUI loginFrame, ConnectHubEngine c) {
        this.cEngine = c;
         this.userAccountManagement = userAccountManagement;
        initComponents();
          setTitle("Sign Up");
          this.loginFrame = loginFrame;
        setLocationRelativeTo(null);
        // اخلي النص شفاف عشان اوجه تعليمات للمستخدم
          jTextField2.setForeground(Color.GRAY);
        jTextField2.setText("Email");

        // إضافة FocusListener لتغيير النص
        jTextField2.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (jTextField2.getText().equals("Email")) {
                    jTextField2.setText("");
                    jTextField2.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (jTextField2.getText().isEmpty()) {
                    jTextField2.setForeground(Color.GRAY);
                    jTextField2.setText("Email");
                }
            }
        });
          jTextField3.setForeground(Color.GRAY);
        jTextField3.setText("Username");
//        jLabel6.setComponentZOrder(this, 0);
        // إضافة FocusListener لتغيير النص
        jTextField3.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (jTextField3.getText().equals("Username")) {
                    jTextField3.setText("");
                    jTextField3.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (jTextField3.getText().isEmpty()) {
                    jTextField3.setForeground(Color.GRAY);
                    jTextField3.setText("Username");
                }
            }
        });
          date.setForeground(Color.GRAY);
        date.setText("YYYY-MM-DD");

        // إضافة FocusListener لتغيير النص
        date.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (date.getText().equals("YYYY-MM-DD")) {
                    date.setText("");
                    date.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (date.getText().isEmpty()) {
                    date.setForeground(Color.GRAY);
                    date.setText("YYYY-MM-DD");
                }
            }
        });
    }
    
    
    // This method validates if the entered date is in the correct format (YYYY-MM-DD)
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        CreateAccount = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 190, -1));

        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 190, -1));

        date.setBackground(new java.awt.Color(204, 204, 204));
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 190, -1));

        CreateAccount.setBackground(new java.awt.Color(153, 153, 153));
        CreateAccount.setText("Create Account");
        CreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccountActionPerformed(evt);
            }
        });
        getContentPane().add(CreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        Password.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 130, -1));

        back.setBackground(new java.awt.Color(153, 153, 153));
        back.setText("<--");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connecthub/signup.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 50, 60));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connecthub/Gradient Background.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountActionPerformed
       String email = jTextField2.getText().trim().toLowerCase();  // Email trimming and lowercase
String password = new String(Password.getPassword()).trim(); // Password trimming
String username = jTextField3.getText().trim();
String dateOfBirth = date.getText().trim();
//String userId = jTextField1.getText().trim();

// Check for missing fields
if (email.isEmpty() || username.isEmpty() || password.isEmpty() || dateOfBirth.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please fill missing fields.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// Validate the date format (YYYY-MM-DD)
if (!userAccountManagement.isValidDate(dateOfBirth)) {
    JOptionPane.showMessageDialog(this, "Invalid date format. Please enter date as YYYY-MM-DD.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// Perform signup
try {
    userAccountManagement.signup(email, username, password, dateOfBirth);
    JOptionPane.showMessageDialog(this, "Account created successfully! Please log in.", "Success", JOptionPane.INFORMATION_MESSAGE);
     System.out.println("User signed up: " + email); // Debugging: Check if user is signed up
     
     cEngine.updateUserDatabase(userAccountManagement.userDatabase);
     
    // After signup, open the login screen and pass the same instance of UserAccountManagement
    this.setVisible(false); // Hide SignUp frame
    new UserAccountManagmentGUI(userAccountManagement, cEngine).setVisible(true); // Pass same instance
} catch (IllegalArgumentException e) {
    JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
} catch (NoSuchAlgorithmException e) {
    JOptionPane.showMessageDialog(this, "An error occurred while processing your request.", "Error", JOptionPane.ERROR_MESSAGE);
}
            

           
    }//GEN-LAST:event_CreateAccountActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false); // Hide the signup frame
    loginFrame.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        // Create an instance of UserAccountManagement (backend)
//        UserAccountManagement userAccountManagement = new UserAccountManagement();
        
        // Create an instance of UserAccountManagmentGUI (login frame)
//        UserAccountManagmentGUI loginFrame = new UserAccountManagmentGUI(userAccountManagement);
        
        // Create and display the SignUpGUI, passing the backend and login frame
//        new SignUpGUI(userAccountManagement, loginFrame, ).setVisible(true);
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateAccount;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton back;
    private javax.swing.JTextField date;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
