/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package connecthub;

/**
 *
 * @author mohamed
 */
public class Logout extends javax.swing.JFrame {
private UserAccountManagmentGUI loginFrame; 
 private UserAccountManagement userAccountManagement;  // Make sure to add this field
    private String currentUserEmail;  // The current logged-in user's email
     private FriendManagement friendManagement;
    /**
     * Creates new form Logout
     */
    public Logout(UserAccountManagmentGUI loginFrame, UserAccountManagement userAccountManagement, String currentUserEmail, FriendManagement friendManagement) {
          this.loginFrame = loginFrame; 
          this.userAccountManagement = userAccountManagement;
        this.currentUserEmail = currentUserEmail;
         this.friendManagement = friendManagement; 
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Friendmanage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel1.setText("hellooooo");

        Friendmanage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Friendmanage.setText("Friendmanage");
        Friendmanage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FriendmanageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logout)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(Friendmanage, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(Friendmanage)
                .addGap(18, 18, 18)
                .addComponent(logout)
                .addGap(131, 131, 131))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
         
 // Display a success message for the logout action
    javax.swing.JOptionPane.showMessageDialog(this, "Logout successful!", "Logout", javax.swing.JOptionPane.INFORMATION_MESSAGE);

    // Method to handle logout                                      
        // Hide current logout frame and show login frame
        this.setVisible(false); 
        loginFrame.setVisible(true); // Show login frame again
    
    }//GEN-LAST:event_logoutActionPerformed

    private void FriendmanageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FriendmanageActionPerformed
        // Create the FriendManagementGUI frame and pass the necessary parameters
    FriendManagementGUI friendManagementGUI = new FriendManagementGUI(userAccountManagement, friendManagement, currentUserEmail);

    // Hide the current Logout frame
    this.setVisible(false);

    // Show the FriendManagementGUI frame
    friendManagementGUI.setVisible(true); 
 
    }//GEN-LAST:event_FriendmanageActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Friendmanage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
